export const glasses = [
  { id: 1, title: "عینک آفتابی کلاسیک مشکی", description: "عینک آفتابی با فریم سبک و لنز تیره مناسب استفاده روزانه", price: 1250000, discount: 10, catId: 1 },
  { id: 2, title: "عینک آفتابی خلبانی طلایی", description: "عینک خلبانی با فریم فلزی و طراحی کلاسیک", price: 1450000, discount: 15, catId: 1 },
  { id: 3, title: "عینک طبی گرد مشکی", description: "عینک طبی سبک با فریم گرد مناسب استفاده روزمره", price: 980000, discount: 0, catId: 2 },
  { id: 4, title: "عینک طبی مربعی نقره ای", description: "عینک طبی با فریم مقاوم و طراحی مدرن", price: 1100000, discount: 12, catId: 2 },
  { id: 5, title: "عینک آفتابی زنانه پروانه ای", description: "عینک زنانه زیبا با طراحی ظریف و لنز تیره", price: 1350000, discount: 20, catId: 3 },
  { id: 6, title: "عینک آفتابی مردانه اسپرت", description: "عینک اسپرت مردانه مناسب فعالیت های روزانه", price: 1500000, discount: 5, catId: 4 },
  { id: 7, title: "عینک آفتابی ویفرر قهوه ای", description: "عینک ویفرر با طراحی کلاسیک و فریم مقاوم", price: 1750000, discount: 10, catId: 1 },
  { id: 8, title: "عینک طبی زنانه نازنین", description: "عینک طبی زنانه سبک و مناسب استفاده طولانی", price: 1050000, discount: 8, catId: 3 },
  { id: 9, title: "عینک طبی مردانه آرمان", description: "عینک مردانه با فریم فلزی مقاوم و سبک", price: 1300000, discount: 0, catId: 4 },
  { id: 10, title: "عینک آفتابی گرد طلایی", description: "عینک گرد با فریم طلایی و طراحی خاص", price: 1650000, discount: 15, catId: 1 },

  { id: 11, title: "عینک آفتابی کلاسیک سرمه ای", description: "عینک آفتابی با فریم سرمه ای و لنز محافظ", price: 1200000, discount: 5, catId: 1 },
  { id: 12, title: "عینک طبی نیم فریم مشکی", description: "عینک طبی نیم فریم با طراحی رسمی و شیک", price: 1400000, discount: 10, catId: 2 },
  { id: 13, title: "عینک زنانه وینتیج قرمز", description: "عینک زنانه با طراحی الهام گرفته از مدل های کلاسیک", price: 1550000, discount: 18, catId: 3 },
  { id: 14, title: "عینک مردانه مستطیلی خاکستری", description: "عینک مردانه با فریم مستطیلی و طراحی مدرن", price: 1150000, discount: 0, catId: 4 },
  { id: 15, title: "عینک آفتابی پولاریزه مشکی", description: "عینک آفتابی با لنز پولاریزه مناسب رانندگی", price: 2100000, discount: 20, catId: 1 },
  { id: 16, title: "عینک طبی فلزی مشکی", description: "فریم فلزی سبک و مقاوم مناسب استفاده روزانه", price: 1250000, discount: 7, catId: 2 },
  { id: 17, title: "عینک زنانه گربه ای صورتی", description: "عینک زنانه با طراحی گربه ای و ظاهری خاص", price: 1800000, discount: 15, catId: 3 },
  { id: 18, title: "عینک مردانه کژوال قهوه ای", description: "عینک مردانه راحت مناسب استفاده روزمره", price: 1350000, discount: 5, catId: 4 },
  { id: 19, title: "عینک آفتابی اسپرت خاکستری", description: "عینک اسپرت با فریم مقاوم و لنز محافظ", price: 1600000, discount: 12, catId: 1 },
  { id: 20, title: "عینک طبی مینیمال شفاف", description: "عینک طبی با طراحی ساده و مدرن", price: 950000, discount: 10, catId: 2 },

  { id: 21, title: "عینک آفتابی زنانه آوا", description: "عینک زنانه شیک با فریم ظریف و طراحی جذاب", price: 1450000, discount: 15, catId: 3 },
  { id: 22, title: "عینک آفتابی مردانه پارسا", description: "عینک مردانه مدرن با طراحی جذاب", price: 1700000, discount: 10, catId: 4 },
  { id: 23, title: "عینک آفتابی فریم شفاف", description: "عینک با فریم شفاف و طراحی جدید", price: 1350000, discount: 0, catId: 1 },
  { id: 24, title: "عینک طبی کلاسیک قهوه ای", description: "عینک طبی مناسب محیط کار و استفاده روزانه", price: 1150000, discount: 8, catId: 2 },
  { id: 25, title: "عینک زنانه بهار طلایی", description: "عینک زنانه سبک و زیبا با فریم فلزی", price: 1600000, discount: 20, catId: 3 },
  { id: 26, title: "عینک مردانه کیان مشکی", description: "عینک مردانه با فریم مقاوم و طراحی شیک", price: 1500000, discount: 5, catId: 4 },
  { id: 27, title: "عینک آفتابی نقره ای", description: "عینک آفتابی با فریم فلزی نقره ای", price: 1900000, discount: 12, catId: 1 },
  { id: 28, title: "عینک طبی فوق سبک", description: "عینک بسیار سبک مناسب استفاده طولانی", price: 1100000, discount: 0, catId: 2 },
  { id: 29, title: "عینک زنانه نیلوفر مشکی", description: "عینک زنانه با طراحی مدرن و فریم مقاوم", price: 1750000, discount: 10, catId: 3 },
  { id: 30, title: "عینک مردانه مهران سرمه ای", description: "عینک مردانه مناسب استایل رسمی", price: 1650000, discount: 15, catId: 4 },

  { id: 31, title: "عینک آفتابی اسپرت مشکی", description: "عینک مناسب ورزش و استفاده در فضای باز", price: 1550000, discount: 10, catId: 1 },
  { id: 32, title: "عینک طبی گرد طلایی", description: "فریم گرد فلزی با طراحی کلاسیک", price: 1450000, discount: 5, catId: 2 },
  { id: 33, title: "عینک زنانه پروانه ای سفید", description: "عینک زنانه با فریم روشن و طراحی خاص", price: 1650000, discount: 20, catId: 3 },
  { id: 34, title: "عینک مردانه فلزی نقره ای", description: "فریم فلزی مقاوم با وزن سبک", price: 1750000, discount: 10, catId: 4 },
  { id: 35, title: "عینک آفتابی وینتیج مشکی", description: "عینک آفتابی با طراحی قدیمی و جذاب", price: 1850000, discount: 15, catId: 1 },
  { id: 36, title: "عینک طبی مربعی مشکی", description: "فریم مربعی مناسب استایل رسمی", price: 1200000, discount: 8, catId: 2 },
  { id: 37, title: "عینک زنانه کلاسیک قهوه ای", description: "عینک شیک مناسب استفاده روزمره", price: 1400000, discount: 5, catId: 3 },
  { id: 38, title: "عینک مردانه ویفرر مشکی", description: "مدل کلاسیک ویفرر با فریم مقاوم", price: 1700000, discount: 12, catId: 4 },
  { id: 39, title: "عینک آفتابی لنز آبی", description: "عینک آفتابی با لنز آبی و فریم سبک", price: 1500000, discount: 0, catId: 1 },
  { id: 40, title: "عینک طبی فریم شفاف", description: "عینک طبی مدرن با فریم شفاف", price: 1300000, discount: 10, catId: 2 },

  { id: 41, title: "عینک زنانه رز طلایی", description: "عینک زنانه ظریف با طراحی لوکس", price: 1900000, discount: 15, catId: 3 },
  { id: 42, title: "عینک مردانه امیر خاکستری", description: "عینک مردانه شیک برای استفاده روزانه", price: 1450000, discount: 5, catId: 4 },
  { id: 43, title: "عینک آفتابی خلبانی مشکی", description: "مدل خلبانی با لنز تیره و فریم مقاوم", price: 1950000, discount: 20, catId: 1 },
  { id: 44, title: "عینک طبی باریک نقره ای", description: "فریم باریک و سبک مناسب محیط کار", price: 1350000, discount: 10, catId: 2 },
  { id: 45, title: "عینک زنانه فریم گرد", description: "عینک زنانه با طراحی گرد و مدرن", price: 1500000, discount: 0, catId: 3 },
  { id: 46, title: "عینک مردانه اسپرت آبی", description: "عینک اسپرت مناسب فعالیت های بیرونی", price: 1650000, discount: 8, catId: 4 },
  { id: 47, title: "عینک آفتابی لوکس طلایی", description: "عینک آفتابی با طراحی لوکس و فریم فلزی", price: 2500000, discount: 15, catId: 1 },
  { id: 48, title: "عینک طبی کژوال قهوه ای", description: "عینک طبی راحت برای استفاده روزانه", price: 1050000, discount: 5, catId: 2 },
  { id: 49, title: "عینک زنانه مهتاب صورتی", description: "عینک زنانه سبک با فریم صورتی", price: 1550000, discount: 12, catId: 3 },
  { id: 50, title: "عینک مردانه رسمی مشکی", description: "عینک مردانه مناسب محیط رسمی و کاری", price: 1800000, discount: 10, catId: 4 },

  { id: 51, title: "عینک آفتابی ساحلی آبی", description: "عینک سبک مناسب سفر و استفاده در ساحل", price: 1450000, discount: 10, catId: 1 },
  { id: 52, title: "عینک طبی دانشجویی مشکی", description: "عینک سبک و اقتصادی مناسب استفاده روزانه", price: 850000, discount: 5, catId: 2 },
  { id: 53, title: "عینک زنانه پریسا زرشکی", description: "عینک زنانه با طراحی خاص و فریم زرشکی", price: 1750000, discount: 18, catId: 3 },
  { id: 54, title: "عینک مردانه سامان قهوه ای", description: "عینک مردانه با طراحی ساده و شیک", price: 1600000, discount: 10, catId: 4 },
  { id: 55, title: "عینک آفتابی رانندگی پولاریزه", description: "لنز پولاریزه مناسب کاهش انعکاس نور", price: 2200000, discount: 15, catId: 1 },
  { id: 56, title: "عینک طبی فریم آبی", description: "عینک طبی با فریم آبی و طراحی جوان پسند", price: 1150000, discount: 8, catId: 2 },
  { id: 57, title: "عینک زنانه النا مشکی", description: "عینک زنانه با فریم مشکی و سبک مدرن", price: 1850000, discount: 20, catId: 3 },
  { id: 58, title: "عینک مردانه رادین نقره ای", description: "فریم فلزی سبک و مناسب استفاده طولانی", price: 1700000, discount: 12, catId: 4 },
  { id: 59, title: "عینک آفتابی مربعی مشکی", description: "عینک آفتابی با فریم مربعی مدرن", price: 1650000, discount: 0, catId: 1 },
  { id: 60, title: "عینک طبی فریم نازک", description: "عینک طبی با فریم نازک و وزن کم", price: 1250000, discount: 10, catId: 2 },

  { id: 61, title: "عینک زنانه یلدا طلایی", description: "عینک زنانه لوکس با فریم طلایی", price: 2100000, discount: 15, catId: 3 },
  { id: 62, title: "عینک مردانه دانیال مشکی", description: "عینک مردانه با طراحی مینیمال", price: 1550000, discount: 5, catId: 4 },
  { id: 63, title: "عینک آفتابی گرد سبز", description: "عینک آفتابی گرد با لنز سبز", price: 1750000, discount: 10, catId: 1 },
  { id: 64, title: "عینک طبی نیم گرد", description: "فریم نیم گرد مناسب استفاده روزانه", price: 1100000, discount: 0, catId: 2 },
  { id: 65, title: "عینک زنانه مارال قهوه ای", description: "عینک زنانه با طراحی ساده و جذاب", price: 1450000, discount: 12, catId: 3 },
  { id: 66, title: "عینک مردانه آرش خاکستری", description: "عینک مردانه مدرن با فریم خاکستری", price: 1650000, discount: 8, catId: 4 },
  { id: 67, title: "عینک آفتابی فریم ضخیم", description: "عینک آفتابی با فریم ضخیم و مقاوم", price: 1850000, discount: 15, catId: 1 },
  { id: 68, title: "عینک طبی سبک مشکی", description: "عینک طبی سبک مناسب استفاده طولانی", price: 990000, discount: 5, catId: 2 },
  { id: 69, title: "عینک زنانه شیوا سفید", description: "عینک زنانه با فریم سفید و طراحی مدرن", price: 1600000, discount: 10, catId: 3 },
  { id: 70, title: "عینک مردانه شاهین طلایی", description: "عینک مردانه فلزی با ظاهر لوکس", price: 1900000, discount: 15, catId: 4 },

  { id: 71, title: "عینک آفتابی لنز دودی", description: "عینک آفتابی با لنز دودی استاندارد", price: 1300000, discount: 10, catId: 1 },
  { id: 72, title: "عینک طبی کلاسیک نقره ای", description: "عینک طبی کلاسیک با فریم فلزی", price: 1400000, discount: 12, catId: 2 },
  { id: 73, title: "عینک زنانه آیلین صورتی", description: "عینک زنانه با طراحی ظریف و جذاب", price: 1750000, discount: 20, catId: 3 },
  { id: 74, title: "عینک مردانه هومن مشکی", description: "عینک مردانه با طراحی رسمی و ساده", price: 1500000, discount: 0, catId: 4 },
  { id: 75, title: "عینک آفتابی فریم چوبی", description: "عینک با ظاهر چوبی و طراحی متفاوت", price: 2300000, discount: 15, catId: 1 },
  { id: 76, title: "عینک طبی مستطیلی", description: "عینک طبی با فریم مستطیلی سبک", price: 1150000, discount: 8, catId: 2 },
  { id: 77, title: "عینک زنانه روژان قرمز", description: "عینک زنانه با فریم قرمز و طراحی خاص", price: 1800000, discount: 10, catId: 3 },
  { id: 78, title: "عینک مردانه بهنام سرمه ای", description: "عینک مردانه مناسب استایل روزمره", price: 1550000, discount: 5, catId: 4 },
  { id: 79, title: "عینک آفتابی ورزشی", description: "عینک مناسب دویدن و فعالیت های ورزشی", price: 2000000, discount: 20, catId: 1 },
  { id: 80, title: "عینک طبی فریم کائوچویی", description: "فریم مقاوم و راحت مناسب استفاده طولانی", price: 1200000, discount: 10, catId: 2 },

  { id: 81, title: "عینک زنانه مهسا مشکی", description: "عینک زنانه شیک با طراحی مینیمال", price: 1650000, discount: 15, catId: 3 },
  { id: 82, title: "عینک مردانه میلاد نقره ای", description: "عینک مردانه با فریم فلزی مقاوم", price: 1750000, discount: 10, catId: 4 },
  { id: 83, title: "عینک آفتابی بیضی طلایی", description: "عینک آفتابی بیضی با فریم طلایی", price: 1900000, discount: 12, catId: 1 },
  { id: 84, title: "عینک طبی بیضی مشکی", description: "عینک طبی با فریم بیضی سبک", price: 1050000, discount: 5, catId: 2 },
  { id: 85, title: "عینک زنانه سارا قهوه ای", description: "عینک زنانه مناسب استایل کلاسیک", price: 1450000, discount: 10, catId: 3 },
  { id: 86, title: "عینک مردانه پویا مشکی", description: "عینک مردانه مدرن و مناسب استفاده روزانه", price: 1600000, discount: 15, catId: 4 },
  { id: 87, title: "عینک آفتابی مدل ساحل", description: "عینک سبک با لنز محافظ نور خورشید", price: 1350000, discount: 0, catId: 1 },
  { id: 88, title: "عینک طبی مدل پزشک", description: "عینک طبی رسمی مناسب محیط کاری", price: 1300000, discount: 8, catId: 2 },
  { id: 89, title: "عینک زنانه رها طلایی", description: "عینک زنانه با فریم فلزی ظریف", price: 1950000, discount: 20, catId: 3 },
  { id: 90, title: "عینک مردانه نوید قهوه ای", description: "عینک مردانه با طراحی کلاسیک", price: 1700000, discount: 10, catId: 4 },

  { id: 91, title: "عینک آفتابی آینه ای", description: "عینک آفتابی با لنز آینه ای جذاب", price: 2150000, discount: 15, catId: 1 },
  { id: 92, title: "عینک طبی مدل اداری", description: "عینک رسمی مناسب محیط کار", price: 1350000, discount: 10, catId: 2 },
  { id: 93, title: "عینک زنانه درسا سفید", description: "عینک زنانه با فریم سفید و سبک", price: 1500000, discount: 5, catId: 3 },
  { id: 94, title: "عینک مردانه سینا خاکستری", description: "عینک مردانه با طراحی مدرن", price: 1650000, discount: 12, catId: 4 },
  { id: 95, title: "عینک آفتابی بزرگ مشکی", description: "عینک بزرگ مناسب استایل مدرن", price: 1800000, discount: 10, catId: 1 },
  { id: 96, title: "عینک طبی کوچک نقره ای", description: "عینک طبی ظریف با فریم فلزی", price: 1150000, discount: 0, catId: 2 },
  { id: 97, title: "عینک زنانه نگار زیتونی", description: "عینک زنانه با رنگ خاص و طراحی زیبا", price: 1700000, discount: 15, catId: 3 },
  { id: 98, title: "عینک مردانه فرهاد مشکی", description: "عینک مردانه ساده و مقاوم", price: 1550000, discount: 8, catId: 4 },
  { id: 99, title: "عینک آفتابی فریم مات", description: "عینک با فریم مات و لنز محافظ", price: 1600000, discount: 10, catId: 1 },
  { id: 100, title: "عینک طبی فریم براق", description: "عینک طبی با فریم براق و طراحی جدید", price: 1400000, discount: 12, catId: 2 },

  { id: 101, title: "عینک زنانه ترانه صورتی", description: "عینک زنانه سبک با فریم صورتی ظریف", price: 1750000, discount: 20, catId: 3 },
  { id: 102, title: "عینک مردانه یاسر سرمه ای", description: "عینک مردانه مناسب استایل رسمی", price: 1800000, discount: 10, catId: 4 },
  { id: 103, title: "عینک آفتابی کلاسیک قهوه ای", description: "عینک آفتابی با طراحی کلاسیک و لنز تیره", price: 1500000, discount: 15, catId: 1 },
  { id: 104, title: "عینک طبی مدرن طلایی", description: "عینک طبی با فریم فلزی طلایی", price: 1600000, discount: 5, catId: 2 },
  { id: 105, title: "عینک زنانه افسانه مشکی", description: "عینک زنانه لوکس با طراحی مدرن", price: 2100000, discount: 15, catId: 3 },
  { id: 106, title: "عینک مردانه کامران نقره ای", description: "عینک مردانه فلزی با وزن سبک", price: 1750000, discount: 12, catId: 4 },
  { id: 107, title: "عینک آفتابی فریم گرد", description: "عینک آفتابی با طراحی گرد کلاسیک", price: 1700000, discount: 10, catId: 1 },
  { id: 108, title: "عینک طبی فریم ضخیم", description: "عینک مقاوم با فریم ضخیم", price: 1250000, discount: 8, catId: 2 },
  { id: 109, title: "عینک زنانه هستی زرشکی", description: "عینک زنانه با رنگ زرشکی خاص", price: 1850000, discount: 18, catId: 3 },
  { id: 110, title: "عینک مردانه پیمان قهوه ای", description: "عینک مردانه با فریم مقاوم و شیک", price: 1650000, discount: 5, catId: 4 },

  { id: 111, title: "عینک آفتابی مدل سفر", description: "عینک سبک مناسب سفر و گردش", price: 1450000, discount: 10, catId: 1 },
  { id: 112, title: "عینک طبی مدل مطالعه", description: "عینک سبک مناسب مطالعه و استفاده طولانی", price: 950000, discount: 5, catId: 2 },
  { id: 113, title: "عینک زنانه الهام طلایی", description: "عینک زنانه ظریف با فریم فلزی", price: 2000000, discount: 20, catId: 3 },
  { id: 114, title: "عینک مردانه سامان مشکی", description: "عینک مردانه کلاسیک و کاربردی", price: 1550000, discount: 10, catId: 4 },
  { id: 115, title: "عینک آفتابی مدل رانر", description: "عینک ورزشی مناسب دویدن و فعالیت بیرونی", price: 2200000, discount: 15, catId: 1 },
  { id: 116, title: "عینک طبی مدل دانشجو", description: "عینک اقتصادی و سبک برای استفاده روزانه", price: 900000, discount: 0, catId: 2 },
  { id: 117, title: "عینک زنانه یاسمین مشکی", description: "عینک زنانه با طراحی مینیمال و شیک", price: 1700000, discount: 12, catId: 3 },
  { id: 118, title: "عینک مردانه سروش خاکستری", description: "عینک مردانه مدرن با فریم خاکستری", price: 1750000, discount: 10, catId: 4 },
  { id: 119, title: "عینک آفتابی مدل شهر", description: "عینک مناسب استفاده روزمره در شهر", price: 1550000, discount: 8, catId: 1 },
  { id: 120, title: "عینک طبی مدل کار", description: "عینک رسمی مناسب محیط کار و اداره", price: 1350000, discount: 10, catId: 2 },

  { id: 121, title: "عینک زنانه مریم قهوه ای", description: "عینک زنانه با طراحی کلاسیک", price: 1600000, discount: 15, catId: 3 },
  { id: 122, title: "عینک مردانه امید مشکی", description: "عینک مردانه سبک و مقاوم", price: 1500000, discount: 5, catId: 4 },
  { id: 123, title: "عینک آفتابی مدل تابستان", description: "عینک آفتابی سبک با لنز تیره", price: 1400000, discount: 10, catId: 1 },
  { id: 124, title: "عینک طبی مدل زمستان", description: "عینک طبی با فریم مقاوم و سبک", price: 1250000, discount: 8, catId: 2 },
  { id: 125, title: "عینک زنانه ندا صورتی", description: "عینک زنانه ظریف با رنگ صورتی", price: 1750000, discount: 20, catId: 3 },
  { id: 126, title: "عینک مردانه مانی آبی", description: "عینک مردانه جوان پسند با فریم آبی", price: 1650000, discount: 10, catId: 4 },
  { id: 127, title: "عینک آفتابی مدل لوکس", description: "عینک آفتابی با طراحی خاص و فریم فلزی", price: 2600000, discount: 15, catId: 1 },
  { id: 128, title: "عینک طبی مدل ساده", description: "عینک طبی با طراحی ساده و سبک", price: 1000000, discount: 5, catId: 2 },
  { id: 129, title: "عینک زنانه کیانا سفید", description: "عینک زنانه با فریم سفید مدرن", price: 1800000, discount: 12, catId: 3 },
  { id: 130, title: "عینک مردانه رضا نقره ای", description: "عینک مردانه با فریم فلزی سبک", price: 1900000, discount: 10, catId: 4 },

  { id: 131, title: "عینک آفتابی مدل آینه ای آبی", description: "عینک با لنز آینه ای آبی مناسب فضای باز", price: 2050000, discount: 15, catId: 1 },
  { id: 132, title: "عینک طبی مدل گرد کوچک", description: "عینک طبی گرد با فریم ظریف", price: 1100000, discount: 0, catId: 2 },
  { id: 133, title: "عینک زنانه باران مشکی", description: "عینک زنانه با طراحی مدرن و زیبا", price: 1850000, discount: 18, catId: 3 },
  { id: 134, title: "عینک مردانه علی قهوه ای", description: "عینک مردانه مناسب استایل روزمره", price: 1550000, discount: 5, catId: 4 },
  { id: 135, title: "عینک آفتابی مدل فشن", description: "عینک آفتابی با طراحی جدید و جذاب", price: 1900000, discount: 10, catId: 1 },
  { id: 136, title: "عینک طبی مدل رسمی", description: "عینک طبی مناسب جلسات و محیط رسمی", price: 1450000, discount: 12, catId: 2 },
  { id: 137, title: "عینک زنانه غزل طلایی", description: "عینک زنانه لوکس با فریم طلایی", price: 2200000, discount: 15, catId: 3 },
  { id: 138, title: "عینک مردانه رامین مشکی", description: "عینک مردانه با طراحی ساده و جذاب", price: 1700000, discount: 8, catId: 4 },
  { id: 139, title: "عینک آفتابی مدل طبیعت", description: "عینک آفتابی مناسب سفر و طبیعت گردی", price: 1800000, discount: 10, catId: 1 },
  { id: 140, title: "عینک طبی مدل راحت", description: "عینک طبی بسیار راحت برای استفاده روزانه", price: 1200000, discount: 5, catId: 2 },

  { id: 141, title: "عینک زنانه نرگس زیتونی", description: "عینک زنانه با فریم زیتونی خاص", price: 1750000, discount: 15, catId: 3 },
  { id: 142, title: "عینک مردانه مازیار خاکستری", description: "عینک مردانه با طراحی مدرن و مقاوم", price: 1850000, discount: 10, catId: 4 },
  { id: 143, title: "عینک آفتابی مدل شهری مشکی", description: "عینک شیک مناسب استفاده روزانه", price: 1600000, discount: 12, catId: 1 },
  { id: 144, title: "عینک طبی مدل حرفه ای", description: "عینک طبی با فریم باکیفیت و سبک", price: 1700000, discount: 10, catId: 2 },
  { id: 145, title: "عینک زنانه سحر قرمز", description: "عینک زنانه با فریم قرمز جذاب", price: 1900000, discount: 20, catId: 3 },
  { id: 146, title: "عینک مردانه کوروش سرمه ای", description: "عینک مردانه مناسب استایل رسمی", price: 1750000, discount: 15, catId: 4 },
  { id: 147, title: "عینک آفتابی مدل رانندگی شب", description: "عینک مناسب کاهش خیرگی نور", price: 2300000, discount: 10, catId: 1 },
  { id: 148, title: "عینک طبی مدل روزانه", description: "عینک سبک برای استفاده روزانه", price: 1050000, discount: 8, catId: 2 },
  { id: 149, title: "عینک زنانه لیانا سفید", description: "عینک زنانه با فریم سفید و طراحی لوکس", price: 2100000, discount: 15, catId: 3 },
  { id: 150, title: "عینک مردانه اشکان مشکی", description: "عینک مردانه مدرن و مقاوم", price: 1800000, discount: 10, catId: 4 },

  { id: 151, title: "عینک آفتابی مدل دریایی", description: "عینک آفتابی سبک با لنز محافظ", price: 1550000, discount: 5, catId: 1 },
  { id: 152, title: "عینک طبی مدل نقره ای", description: "عینک طبی با فریم فلزی نقره ای", price: 1500000, discount: 10, catId: 2 },
  { id: 153, title: "عینک زنانه رویا مشکی", description: "عینک زنانه شیک با طراحی مدرن", price: 1850000, discount: 18, catId: 3 },
  { id: 154, title: "عینک مردانه حمید قهوه ای", description: "عینک مردانه کلاسیک و سبک", price: 1600000, discount: 5, catId: 4 },
  { id: 155, title: "عینک آفتابی مدل جوان", description: "عینک آفتابی با طراحی جوان پسند", price: 1750000, discount: 12, catId: 1 },
  { id: 156, title: "عینک طبی مدل مدرن مشکی", description: "عینک طبی با طراحی جدید و فریم سبک", price: 1350000, discount: 10, catId: 2 },
  { id: 157, title: "عینک زنانه ستاره طلایی", description: "عینک زنانه لوکس با طراحی خاص", price: 2300000, discount: 20, catId: 3 },
  { id: 158, title: "عینک مردانه امین نقره ای", description: "عینک مردانه با فریم فلزی مقاوم", price: 1900000, discount: 15, catId: 4 },
  { id: 159, title: "عینک آفتابی مدل لنز سبز", description: "عینک آفتابی با لنز سبز و فریم سبک", price: 1650000, discount: 10, catId: 1 },
  { id: 160, title: "عینک طبی مدل دانشجویی آبی", description: "عینک سبک و اقتصادی با فریم آبی", price: 950000, discount: 5, catId: 2 },

  { id: 161, title: "عینک زنانه دنیا صورتی", description: "عینک زنانه ظریف و سبک", price: 1700000, discount: 15, catId: 3 },
  { id: 162, title: "عینک مردانه سعید مشکی", description: "عینک مردانه مناسب استفاده روزمره", price: 1550000, discount: 8, catId: 4 },
  { id: 163, title: "عینک آفتابی مدل طلایی", description: "عینک آفتابی با فریم فلزی طلایی", price: 2100000, discount: 15, catId: 1 },
  { id: 164, title: "عینک طبی مدل ظریف", description: "عینک طبی با فریم نازک و طراحی شیک", price: 1400000, discount: 10, catId: 2 },
  { id: 165, title: "عینک زنانه آتنا قهوه ای", description: "عینک زنانه با طراحی کلاسیک", price: 1600000, discount: 12, catId: 3 },
  { id: 166, title: "عینک مردانه وحید خاکستری", description: "عینک مردانه با فریم خاکستری مدرن", price: 1700000, discount: 5, catId: 4 },
  { id: 167, title: "عینک آفتابی مدل مینیمال", description: "عینک ساده و سبک با طراحی مینیمال", price: 1500000, discount: 10, catId: 1 },
  { id: 168, title: "عینک طبی مدل کائوچویی", description: "عینک طبی مقاوم با فریم کائوچویی", price: 1300000, discount: 8, catId: 2 },
  { id: 169, title: "عینک زنانه دریا آبی", description: "عینک زنانه با رنگ آبی خاص", price: 1850000, discount: 20, catId: 3 },
  { id: 170, title: "عینک مردانه شهاب سرمه ای", description: "عینک مردانه شیک برای استایل رسمی", price: 1800000, discount: 10, catId: 4 },

  { id: 171, title: "عینک آفتابی مدل تابان", description: "عینک آفتابی با لنز محافظ نور خورشید", price: 1700000, discount: 15, catId: 1 },
  { id: 172, title: "عینک طبی مدل باریک", description: "عینک طبی سبک با فریم باریک", price: 1150000, discount: 5, catId: 2 },
  { id: 173, title: "عینک زنانه نازگل مشکی", description: "عینک زنانه با طراحی شیک و مدرن", price: 1900000, discount: 18, catId: 3 },
  { id: 174, title: "عینک مردانه کاوه قهوه ای", description: "عینک مردانه کلاسیک و مقاوم", price: 1750000, discount: 12, catId: 4 },
  { id: 175, title: "عینک آفتابی مدل کوهستان", description: "عینک مقاوم مناسب طبیعت گردی", price: 2400000, discount: 15, catId: 1 },
  { id: 176, title: "عینک طبی مدل فریم گرد", description: "عینک طبی با فریم گرد و طراحی کلاسیک", price: 1250000, discount: 10, catId: 2 },
  { id: 177, title: "عینک زنانه پرنیا سفید", description: "عینک زنانه با فریم سفید سبک", price: 1800000, discount: 15, catId: 3 },
  { id: 178, title: "عینک مردانه آراد مشکی", description: "عینک مردانه جوان پسند و مدرن", price: 1650000, discount: 10, catId: 4 },
  { id: 179, title: "عینک آفتابی مدل حرفه ای", description: "عینک آفتابی با کیفیت و لنز مقاوم", price: 2500000, discount: 20, catId: 1 },
  { id: 180, title: "عینک طبی مدل اقتصادی", description: "عینک طبی مناسب استفاده روزمره با قیمت اقتصادی", price: 850000, discount: 5, catId: 2 },

  { id: 181, title: "عینک زنانه یگانه طلایی", description: "عینک زنانه لوکس با فریم طلایی ظریف", price: 2200000, discount: 15, catId: 3 },
  { id: 182, title: "عینک مردانه بهروز نقره ای", description: "عینک مردانه فلزی با طراحی مدرن", price: 1950000, discount: 10, catId: 4 },
  { id: 183, title: "عینک آفتابی مدل شهری طلایی", description: "عینک آفتابی مناسب استفاده روزانه در شهر", price: 1850000, discount: 12, catId: 1 },
  { id: 184, title: "عینک طبی مدل رسمی مشکی", description: "عینک رسمی با فریم مشکی مقاوم", price: 1450000, discount: 8, catId: 2 },
  { id: 185, title: "عینک زنانه آیدا زرشکی", description: "عینک زنانه با رنگ زرشکی و طراحی جذاب", price: 2000000, discount: 20, catId: 3 },
  { id: 186, title: "عینک مردانه بابک خاکستری", description: "عینک مردانه سبک و مناسب استفاده روزانه", price: 1700000, discount: 10, catId: 4 },
  { id: 187, title: "عینک آفتابی مدل شیشه ای", description: "عینک آفتابی با فریم شفاف مدرن", price: 1600000, discount: 5, catId: 1 },
  { id: 188, title: "عینک طبی مدل سبک طلایی", description: "عینک طبی سبک با فریم فلزی طلایی", price: 1550000, discount: 12, catId: 2 },
  { id: 189, title: "عینک زنانه سوگند صورتی", description: "عینک زنانه ظریف با فریم صورتی", price: 1750000, discount: 15, catId: 3 },
  { id: 190, title: "عینک مردانه فرزاد مشکی", description: "عینک مردانه مقاوم با طراحی ساده", price: 1650000, discount: 8, catId: 4 },

  { id: 191, title: "عینک آفتابی مدل کلاسیک طلایی", description: "عینک آفتابی کلاسیک با فریم فلزی طلایی", price: 2100000, discount: 15, catId: 1 },
  { id: 192, title: "عینک طبی مدل مدرن خاکستری", description: "عینک طبی با فریم خاکستری و طراحی جدید", price: 1350000, discount: 10, catId: 2 },
  { id: 193, title: "عینک زنانه مهتاب سفید", description: "عینک زنانه سبک با طراحی مینیمال", price: 1850000, discount: 20, catId: 3 },
  { id: 194, title: "عینک مردانه نیما قهوه ای", description: "عینک مردانه با فریم قهوه ای کلاسیک", price: 1750000, discount: 12, catId: 4 },
  { id: 195, title: "عینک آفتابی مدل پولاریزه حرفه ای", description: "عینک پولاریزه با لنز مناسب رانندگی و سفر", price: 2700000, discount: 20, catId: 1 },
  { id: 196, title: "عینک طبی مدل مینیمال مشکی", description: "عینک طبی ساده و سبک با طراحی مینیمال", price: 1200000, discount: 5, catId: 2 },
  { id: 197, title: "عینک زنانه آوا قهوه ای", description: "عینک زنانه با فریم قهوه ای و طراحی مدرن", price: 1800000, discount: 15, catId: 3 },
  { id: 198, title: "عینک مردانه کیان نقره ای", description: "عینک مردانه با فریم فلزی نقره ای", price: 1900000, discount: 10, catId: 4 },
  { id: 199, title: "عینک آفتابی مدل اسپرت حرفه ای", description: "عینک آفتابی مقاوم مناسب فعالیت های ورزشی", price: 2300000, discount: 15, catId: 1 },
  { id: 200, title: "عینک طبی مدل پریمیوم", description: "عینک طبی با کیفیت بالا و فریم سبک", price: 2200000, discount: 10, catId: 2 }
];